### ISSUE TITLE
nausicaa: where is the current project home?

### ISSUE THREAD

**Issue by salewski** [marcomaggi/marcomaggi.github.io#2]
While working on PR #1 it was noticed that a similar fix might need to be applied to the file:
```
    docs/ikarus.html
```
for the "Nausicaa" library, which is currently pointing to a non-existent URL:
```
    http://marcomaggi.github.com/nausicaa.html
```
According to [this 2009-10-20 post](https://groups.google.com/g/comp.lang.scheme/c/K2NbjPFEIyU/m/KW4fD1KCN5wJ) to the `comp.lang.scheme` newsgroup, that was the correct URL for the project at that point.

However, it is not clear if the library has an official home currently. Neither of the following exist, either:
```
    https://marcomaggi.github.io/nausicaa.html
    https://marcomaggi.github.com/marcomaggi/nausicaa
```
and searching for the project more broadly turned up the GitHub repo:
```
   https://github.com/okuoku/nausicaa
```

Does the Nauticaa library currently have an official home to which the URL should point?

**Comment by marcomaggi** [comment]
Nausicaa is abandonware.  okuoku had a fork because she was using it (I think) as test code for a Scheme implementation (mosh).  Just forget it.
